crawler:
  maxDepth: 2
  sourcePriorityOrder: CROSSREF,ARXIV,SCOPUS,CHROME
  crossref:
    baseUrl: http://api.crossref.org
    apiKey:
    secret:
    maxRepeatingRequests: 5
  scholars:
    baseUrl: https://serpapi.com
    apiKey: 267111d446ba95094c614285d6063acf4bc688bd4914482f83ba959a985398eb